protobuf APIv2: Add UnimplementedCLIServer to CLI struct
This is a change required by grpc-go >= v1.30.0, cf.
https://github.com/grpc/grpc-go/commit/ad51f572fd270f2323e3aa2c1d2775cab9087af2

Otherwise build fails with:

```
rpc/rpc.go:61:30: cannot use c (variable of type *CLI) as CLIServer value in argument to RegisterCLIServer: *CLI does not implement CLIServer (missing method mustEmbedUnimplementedCLIServer)
```