protobuf APIv2: Update Makefile, go.mod and rpc.proto
Switch from github.com/golang/protobuf to google.golang.org/protobuf to
transition to protobuf API v2. Update the commands to generate the code
in Makefile. Details below.

=== go.mod: protobuf

v1.20.0 marked the transition to the protobuf API v2, this is the
minimul version we can use, in theory.

v1.25.0 introduced the method CheckValid() for the protobuf Timestamp
type, and we want to use it.

=== go.mod: grpc

We need version 1.32 at least, otherwise the code generated fails to
compile with:

```
rpc/rpc_grpc.pb.go:20:16: undefined: grpc.SupportPackageIsVersion7
rpc/rpc_grpc.pb.go:296:31: undefined: grpc.ServiceRegistrar
```

=== Makefile: protoc-gen-go-grpc

The version of protoc-gen-go-grpc is not aligned with the versions of
go-grpc, even though it all comes from https://github.com/grpc/grpc-go/.
The list of the protoc-gen-go-grpc versions available can be found at:
https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc?tab=versions